### ISSUE TITLE
reshape keep from pycombat_seq

### ISSUE THREAD

**Issue by ceesu** [epigenelabs/inmoose#10]
Hello, thanks for developing this package. I found when using pycombat_seq from your package that if `counts` is a matrix of `dtype('float64')` and size (10000,x) and `batch` is a list of length x, then the line 76

`keep &= counts[:, batch == b].sum(axis=1) > 0`

Generates the error:

`non-broadcastable output operand with shape (10000,) doesn't match the broadcast shape (10000,10000)`

It seems this could be avoided by changing the variable initialization in line 73 as follows: 

`keep = np.full((counts.shape[0],), True).reshape(-1,1)`

**Comment by ceesu** [comment]
Actually, it seems like I can avoid the error more easily by setting my inputs to numpy arrays, using `.toarray()` for the csr matrix and `np.array()` for the batch variable.

**Comment by EpigeneMax** [comment]
Hello, and thanks for reporting this.
Indeed, `pycombat_seq` requires a dense array for the count matrix. This constraint stems from the way arrays are handled in the underlying C++ code.
We could add a check for the input matrix though.

**Comment by ceesu** [comment]
Sure sounds good. It seems like a small change but I could send a PR if you like.

**Comment by EpigeneMax** [comment]
If you have time for it, we happily welcome contributions :)
