### ISSUE TITLE
Provide a real logger and stop overriding the root one

### ISSUE THREAD

**Issue by VasLem** [epigenelabs/inmoose#49]
Thank you for the very useful tool. I am having issues reducing the verbosity of the tool, in particular pycomat_norm. I have checked the code and everywhere is used the logging module directly, also the defaults are changed, I cannot even silence it by redirecting stdout and stderr outside of the function. Would you accept a pull request where a package logger is used instead of the root one?

**Comment by EpigeneMax** [comment]
Hello @VasLem, thank you for you valuable feedback.
Yes, we are open to external contributions :)

**Comment by EpigeneMax** [comment]
closed by #50
