### ISSUE TITLE
Consensus Clustering

### ISSUE THREAD

**Issue by soleneweill** [epigenelabs/inmoose#5]
## WHAT ?
Clustering allows to discover distinct and non overlapping sub-populations within a population on gene expression data. But determining the number of clusters to use and assessing the confidence in the produced clusters is not trivial. 

Consensus clustering is a resampling based algorithm allowing to address these issues by combining multiple runs of clustering. 

## WHY ?
To date there is no python distributed implementation of consensus clustering in python. 

## HOW ?
The proposed feature will be the implementation of consensus clustering according to Monti, S., Tamayo, P., Mesirov, J. et al. Consensus Clustering: A Resampling-Based Method for Class Discovery and Visualization of Gene Expression Microarray Data. Machine Learning 52, 91–118 (2003). https://doi.org/10.1023/A:1023949509487

Note that the R Bioconductor package [consensusclusterplus](https://bioconductor.org/packages/release/bioc/html/ConsensusClusterPlus.html) is based on the same paper.

**Comment by EpigeneMax** [comment]
Implemented in #7.
