### ISSUE TITLE
Issue running ComBat-seq

### ISSUE THREAD

**Issue by richard-k-perez** [epigenelabs/inmoose#79]
Hello,

I am trying to run pycombat_seq but encountering the following error (see below). I believe the issue is with _isAllZero function from edgepy utils. DGEList.__init__ checks for a pandas dataframe and converts the data into a dataframe if not already in that form. Then the dataframe is passed to _isAllZero() which expects an array. if np.isnan(check_range[0]) is performed on a pandas Series instead of the array it expects leading to the error. I think a quick fix to the  check_range object or the _isAllZero function should fix it.

Thanks,
Richard 

"
File ~/opt/anaconda3/lib/python3.9/site-packages/inmoose/pycombat/pycombat_seq.py:111, in pycombat_seq(counts, batch, covar_mod, shrink, shrink_disp, gene_subset_n, ref_batch, na_cov_action)
    108 countsOri = counts.copy()
    109 counts = counts[keep, :]
--> 111 dge_obj = DGEList(counts=counts)
    113 ####### Estimate gene-wise dispersions within each batch #######
    114 LOGGER.info("Estimating dispersions")

File ~/opt/anaconda3/lib/python3.9/site-packages/inmoose/edgepy/DGEList.py:125, in DGEList.__init__(self, counts, lib_size, norm_factors, samples, group, group_col, genes, remove_zeroes)
    119 if not isinstance(counts, pd.DataFrame):
    120     counts = pd.DataFrame(
    121         counts,
    122         index=[f"gene{i}" for i in range(ntags)],
    123         columns=[f"sample{i}" for i in range(nlibs)],
    124     )
--> 125 _isAllZero(
    126     counts
    127 )  # don't really care about all-zeroes, but do want to protect against NaN, infinite and negative values
    129 # Check lib_size
    130 if lib_size is None:

File ~/opt/anaconda3/lib/python3.9/site-packages/inmoose/edgepy/utils.py:45, in _isAllZero(y)
     43     return False
     44 check_range = (np.amin(y), np.nanmax(y))
---> 45 if np.isnan(check_range[0]):
     46     raise ValueError("NaN counts are not allowed")
     47 if check_range[0] < 0:

File ~/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py:1527, in NDFrame.__nonzero__(self)
   1525 @final
   1526 def __nonzero__(self) -> NoReturn:
-> 1527     raise ValueError(
   1528         f"The truth value of a {type(self).__name__} is ambiguous. "
   1529         "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
   1530     )

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()."

**Comment by EpigeneMax** [comment]
Hi @richard-k-perez, thank you for reporting this.

I was not able to reproduce the precise example you describe but I realized that `_isAllZero` had inconsistent behaviors between numpy arrays and pandas dataframes.
I modified the function to always fallback to numpy arrays (see #81), which should solve your issue.
