### ISSUE TITLE
Set minimal `scipy` version

### ISSUE THREAD

**Issue by enryH** [epigenelabs/inmoose#94]
With `scipy==1.10.1` I could not import `false_discovery_control` which was added in scipy `1.11`. You might want to set a lower limit to make that dependency explicit: 

`from scipy.stats import combine_pvalues, false_discovery_control`

**Comment by enryH** [comment]
reference: https://docs.scipy.org/doc/scipy-1.11.0/release/1.11.0-notes.html

**Comment by EpigeneMax** [comment]
Hello @enryH, thanks for reporting this.

Until the next version is released, we can workaround this by forcing the version of `scipy`, _e.g._:
```
pip install scipy==1.14.0
pip install inmoose
```

**Comment by enryH** [comment]
Welcome! I was working on a project which was restrictive with the old scipy version for now reason, so I not noticed. Updating to 1.14.1 worked perfectly.
